### ISSUE TITLE
Space not found

### ISSUE THREAD

**Issue by EdwinLocker** [fablabs-ch/fablabsch#50]
https://fablab.ch/admin/fablabsch/event/add/

Je n'arrive pas à voir les différents "spaces" disponibles quand je commence à écrire dedans le champ.

**Comment by bfritscher** [comment]
Adblock? ou un autre plugin?

![image](https://user-images.githubusercontent.com/338973/156417353-3dcf8a97-34e6-4fab-81cf-cd312d541af8.png)

**Comment by bfritscher** [comment]
Maybe permission problem I added view space back
